image: node:6.10.3

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run eslint
  tags:
    v*.*.*:
      - step:
          caches:
            - node
          script:
            - mv .npmrc_config .npmrc
            - npm publish